# This file stores the flash_commands for each mcus
# Previous version KCONFIG_CONFIG was needed now it is automaticly added when make flash is called
# version : 0.1
# tested/supported flash methods :
#  - make flash
#  - sdcard_flash
#  - flashtool.py
#  - mount/cp/umount (for rp2040)
 

[m8p]
klipper_section: mcu
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can1 -u c0f599d7bb14 -r
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -f ~/klipper/out/klipper.bin -d /dev/serial/by-id/usb-katapult_stm32h723xx_3E000A001251313236343430-if00

[ebb36_toolhead]
klipper_section: mcu toolhead_mcu
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can1 -u cd407005594f 

[ebb36_t0]
klipper_section: mcu mmu0
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u cc8f39d714ce 

[ebb36_t1]
klipper_section: mcu mmu1
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u c2357f5873d7 

[ebb36_t2]
klipper_section: mcu mmu2
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 31fb8c95fbfd 

[ebb36_t3]
klipper_section: mcu mmu3
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 8579c5130649 

[ebb36_t4]
klipper_section: mcu mmu4
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 7d42f7c43687 

[ebb36_t5]
klipper_section: mcu mmu5
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 3efbe46e5d5f 

[ebb36_t6]
klipper_section: mcu mmu6
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u f050daaa5448 

[ebb36_t7]
klipper_section: mcu mmu7
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 49abda4839e6 

[slb_t8]
klipper_section: mcu mmu8
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 2b62794dd839 

[slb_t9]
klipper_section: mcu mmu9
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 74d5b2c5d1ca 

[slb_t10]
klipper_section: mcu mmu10
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 8f4f90d95a7f 

[slb_t11]
klipper_section: mcu mmu11
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u e78e90e44d82 

[slb_t12]
klipper_section: mcu mmu12
action_command: ~/klippy-env/bin/python3 ~/katapult/scripts/flashtool.py -i can0 -u 134943460803 
